version: "3.7"

services:
    database:
        image: postgres
        container_name: inscricoes
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=inscri_api
        volumes: 
            - pgdata:/data/postgres

volumes: 
    pgdata:
        driver: local